const config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a9c7ff",
        "on-surface": "#191c1d",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-error-container": "#93000a",
        surface: "#f8f9fa",
        "on-tertiary-fixed": "#001f29",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001b3d",
        "on-primary": "#ffffff",
        outline: "#747780",
        "surface-container": "#edeeef",
        "on-tertiary-fixed-variant": "#004d62",
        "on-tertiary-container": "#009fc7",
        tertiary: "#001a23",
        "on-secondary-fixed-variant": "#004f4f",
        "primary-container": "#002b5b",
        "tertiary-fixed-dim": "#5ad4ff",
        "on-primary-container": "#7594ca",
        "tertiary-fixed": "#baeaff",
        "tertiary-container": "#00303e",
        secondary: "#006a6a",
        "inverse-surface": "#2e3132",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#76d6d5",
        error: "#ba1a1a",
        "secondary-container": "#90efef",
        background: "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "inverse-primary": "#a9c7ff",
        "on-secondary-container": "#006e6e",
        "on-surface-variant": "#43474f",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c4c6d0",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#002020",
        "on-background": "#191c1d",
        primary: "#001736",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#93f2f2",
        "surface-tint": "#405f91",
        "surface-dim": "#d9dadb",
        "on-primary-fixed-variant": "#264778",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
